name: gradient_progress_indicator
description: A new Flutter package project.
version: 1.0.0+3
repository: https://github.com/otonielduarte/gradient-progress-indicator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: